### ISSUE TITLE
IO/Memory/GC issues..

### ISSUE THREAD

**Issue by thomasf** [CIRCL/IP-ASN-history#2]
In the db importer there is an awful amount of memory/io being used instead of buffered reads and writes.. One example is the file splitter which does this:

``` python
               temp.seek(prec)
                # Get the text we want to put in the new file
                copy = temp.read(actual - prec)
                # Write the new file
                open(new_file, 'w').write(copy)
```

Just by doing that might very well generates enough garbage for the gc to handle so that parallel execution gains are negated.

I am runnung this in python 2 right now but from what I read in the py3 docs, python3 would not stream this either (?)

I changed bgpdump to utilize the -O option for output because python does not need to be involved there..

For me the dbimport memory consumption has gone down from topping arount 12gb ram to 6mb for the most part.. (except that I have still not located the last location where the full parsed bgpdump seems to be read into memory)

I'll make my changes available when I'm done, for now I have forked this full repository into my docker container repo.

**Comment by thomasf** [comment]
My WIP is here .. https://github.com/alkasir/docker-IP-ASN-history 

There's still more work for me to do in the other repository.. I have not been able to call the web service and get a reply yet.. Also my changes are primarily focused on getting solid performance from it all, for me parallel  aspect of running the import/downlader services are not important at all.

**Comment by thomasf** [comment]
I guess that these are the things that might be relevant for the topic of this issue.

https://github.com/alkasir/docker-IP-ASN-history/commit/bfe00eb2a9ede7e499695d237c6c7e3b1c411ea4

https://github.com/alkasir/docker-IP-ASN-history/commit/e5acceec6e9c2cd17f2d51bc85a26f54bd1f38e2

https://github.com/alkasir/docker-IP-ASN-history/commit/19f9b409dd72e5f825f310ba6438afb9a66993a2

**Comment by thomasf** [comment]
I'll just make a go port of everything

**Comment by Rafiot** [comment]
Sorry for the late answer, it seems I was not subscribed to the notifications... Thank you for the hints and I will see how to implement it in python.

I will also keep an eye on the go port, that sounds interesting :)

**Comment by thomasf** [comment]
Thanks for getting back.

Porting small things is always a pleasure just because having a reference I can know exactly how done I am at any time :)

The go community seemed to be lacking this category of utilities so I just decided to do the work.

**Comment by thomasf** [comment]
the -m switch of bgpdump should simplify your implementation as well if you get back working on it some day.
